## Copyright (c) 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy a Data Lakehouse with MDS on OCI"
stackDescription: "Deploy a Data Lakehouse on OCI with MySQL Database Service (including multinode scenario)"
schemaVersion: 1.2.0
version: "20201104"
locale: "en"

variableGroups:
  - title: "General Configuration"
    visible: false
    variables:
      - tenancy_ocid
      - region
      - ssh_authorized_keys_path
      - ssh_private_key_path
      - private_key_path
      - release
      - node_image_id
      - label_prefix
      - mysql_db_system_display_name
      - mysql_db_system_description
      - mysql_db_system_maintenance_window_start_time
      - mysql_db_system_hostname_label
      - mysql_db_system_fault_domain
      - data_lake_bucket_name
      - data_lake_bucket_access_type
      - data_lake_bucket_name_storage_tier

  - title: Required Variables
    visible: true
    variables:
      - compartment_ocid
      - availability_domain_name
      - admin_password
      - numberOfNodes
      - db_password
      - show_advanced
      - mysql_heatwave_enabled

  - title: Network Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - vcn
      - vcn_cidr

  - title: Load Balancer Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - lb_shape 
      - flex_lb_min_shape
      - flex_lb_max_shape 

  - title: File Storage Service Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - use_shared_storage

  - title: Bastion Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - use_bastion_service
      - bastion_shape
      - bastion_flex_shape_ocpus
      - bastion_flex_shape_memory

  - title: Compute Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - ssh_public_key
      - node_shape
      - instance_os
      - linux_os_version
      - node_flex_shape_ocpus
      - node_flex_shape_memory  

  - title: Object Storage Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - data_lake_bucket_name
      - data_lake_bucket_access_type
      - data_lake_bucket_name_storage_tier

  - title: MDS Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
      - admin_username
      - mysql_shape      
      - mds_instance_name
      - mysql_db_system_data_storage_size_in_gb
      - mysql_is_highly_available
      - mysql_heatwave_shape
      - mysql_heatwave_cluster_size

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."

  region:
    type: oci:identity:region:name
    visible: false
    required: true
    title: ${Messages.solutionsHub.genericVariables.region.title()}
    description: ${Messages.solutionsHub.genericVariables.region.description()}

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: false
    visible: true
    title: "Availability Domain to be chosen"
    description: "Choose the Availability Domain where your instances and MDS will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  numberOfNodes:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "How many nodes?"
    description: "Choose number of instances to be deployed (more then one will create LoadBalancer)."

  node_shape:
    type: oci:core:instanceshape:name
    title: "Select a shape for the Compute Instance(s)"
    dependsOn:
      compartmentId: compartment_ocid

  node_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 6
    title: "Flex Shape Memory (GB)"
    description: "Choose number of GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - node_shape
            - "VM.Standard.E3.Flex"
          - eq:
            - node_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - node_shape
            - "VM.Standard.A1.Flex"
          - eq:
            - node_shape
            - "VM.Optimized3.Flex"

  node_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - node_shape
            - "VM.Standard.E3.Flex"
          - eq:
            - node_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - node_shape
            - "VM.Standard.A1.Flex"
          - eq:
            - node_shape
            - "VM.Optimized3.Flex"

  use_bastion_service:
    type: boolean
    title: "Use OCI Bastion Service?"
    description: "Check if you want to use OCI Bastion Service instead of Bastion VM."
    default: false
    visible:
      and:
        - gt:
          - numberOfNodes
          - 1      
        - eq:
          - show_advanced
          - true  

  bastion_shape:
    type: oci:core:instanceshape:name
    required: false
    title: "BastionVM Shape"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    default: "VM.Standard.E4.Flex"
    visible:
      and:
        - gt:
          - numberOfNodes
          - 1      
        - eq:
          - use_bastion_service
          - false  
    dependsOn:
      compartmentId: ${compartment_ocid}

  bastion_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "BastionVM Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - gt:
          - numberOfNodes
          - 1      
        - eq:
          - use_bastion_service
          - false         
        - or:
          - eq:
            - bastion_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - bastion_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - bastion_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - bastion_shape 
            - "VM.Optimized3.Flex"

  bastion_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "BastionVM Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - gt:
          - numberOfNodes
          - 1      
        - eq:
          - use_bastion_service
          - false         
        - or:
          - eq:
            - bastion_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - bastion_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - bastion_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - bastion_shape 
            - "VM.Optimized3.Flex"

  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"
    visible: 
      gt:
        - numberOfNodes
        - 1

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"
        - gt:
          - numberOfNodes
          - 1

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"
        - gt:
          - numberOfNodes
          - 1
  
  vcn:
    type: string
    visible: false
    required: true
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_display_name.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_display_name.description()}

  vcn_cidr:
    type: string
    visible: false
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_cidr.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_cidr.description()}

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: Compartment where you want to create the solution resources

  admin_username:
    type: string
    required: true
    title: MDS Admin Username
    description: MySQL Database Service's admin username
    minLength: 1
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"

  admin_password:
    type: password
    required: true
    title: MDS Admin User's Password
    description: Password for MySQL Database Service's admin user
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  mysql_is_highly_available:
    title: "Deploy High Availability for MDS"
    type: boolean
    default: false

  db_password:
    type: password
    required: true
    title: MySQL User Password
    description: MySQL User Password
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  mds_instance_name:
    type: string
    required: true
    title: MDS Instance name

  mysql_heatwave_enabled:
    type: boolean
    title: "Enable MySQL HeatWave"
    description: "Defines whether a MySQL HeatWave cluster is enabled"
  
  mysql_heatwave_shape:
    type: string
    title: "MySQL HeatWave Shape"
    description: "The shape to be used instead of mysql_shape when mysql_heatwave_enabled = true."
    visible:
        and:
          - mysql_heatwave_enabled
          - show_advanced

  mysql_heatwave_cluster_size:
    type: string
    title: "MySQL HeatWave Cluster Size"
    description: "Number of MySQL HeatWave nodes to be created."
    visible:
        and:
          - mysql_heatwave_enabled
          - show_advanced

  data_lake_bucket_name:
    type: string
    required: true
    title: Data Lake bucket name

  data_lake_bucket_access_type:
    type: string
    required: true
    title: Data Lake bucket Access Type

  data_lake_bucket_storage_tier:
    type: string
    required: true
    title: Data Lake bucket Storage Tier

  use_shared_storage:
    type: boolean
    visible:
      gt:
        - numberOfNodes
        - 1
    default: true
    required: false
    title: "Use OCI File Storage Service"
    description: "Check the box to use OCI FSS for multinode setup (shared directory)."

  mysql_shape:
    type: enum
    required: false
    default: "MySQL.VM.Standard.E3.1.8GB"
    title: "MDS Shape"
    description: "Choose the MySQL Database System Shape for your MDS deployments."
    enum:
      - "VM.Standard.E2.1"
      - "VM.Standard.E2.2"
      - "VM.Standard.E2.4"  
      - "VM.Standard.E2.8"
      - "MySQL.VM.Standard.E3.1.8GB"
      - "MySQL.VM.Standard.E3.1.16GB"      
      - "MySQL.VM.Standard.E3.2.32GB"
      - "MySQL.VM.Standard.E3.4.64GB"
      - "MySQL.VM.Standard.E3.8.128GB"
      - "MySQL.VM.Standard.E3.16.256GB"
      - "MySQL.VM.Standard.E3.24.384GB"
      - "MySQL.VM.Standard.E3.32.512GB"
      - "MySQL.VM.Standard.E3.48.768GB"    
      - "MySQL.VM.Standard.E3.64.1024GB"  
      - "MySQL.HeatWave.VM.Standard.E3" 
    visible: 
        and:
          - show_advanced
          - not:
            - mysql_heatwave_enabled

  mysql_db_system_display_name:
    type: string
    required: true
    title: MySQL Database Service display name
  
  mysql_db_system_data_storage_size_in_gb:
    type: number
    title: "MySQL Data Storage Size in GB"
    default: "50"

  mysql_db_system_description:
    type: string
    required: true
    title: MySQL Database Service description 

  linux_os_version:
    type: enum
    required: false
    visible: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for WordPress host."
    default: "8"
    enum:
      - "8"

  instance_os:
    type: enum
    required: false
    visible: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for WordPress host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"
